# Generated by Django 5.2.2 on 2025-08-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soiree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadhesion',
            name='miniature_video',
            field=models.ImageField(blank=True, help_text='Miniature de la vidéo (recommandé: 16:9, max 2MB)', null=True, upload_to='miniatures/demandes/'),
        ),
        migrations.AddField(
            model_name='demandeadhesion',
            name='video_etablissement',
            field=models.FileField(blank=True, help_text="Vidéo de présentation de l'établissement (MP4, AVI, MOV recommandés)", null=True, upload_to='videos/demandes/'),
        ),
        migrations.AddField(
            model_name='service',
            name='miniature_video',
            field=models.ImageField(blank=True, help_text='Miniature de la vidéo (recommandé: 16:9, max 2MB)', null=True, upload_to='miniatures/videos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='video_etablissement',
            field=models.FileField(blank=True, help_text="Vidéo de présentation de l'établissement (MP4, AVI, MOV recommandés)", null=True, upload_to='videos/etablissements/'),
        ),
    ]
