# Generated by Django 5.2.2 on 2025-08-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soiree', '0002_demandeadhesion_miniature_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionnaire',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Numéro téléphone'),
        ),
    ]
