# Generated by Django 5.2.2 on 2025-08-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soiree', '0003_alter_gestionnaire_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro téléphone'),
        ),
    ]
