# Generated by Django 5.2.2 on 2025-08-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soiree', '0004_alter_profile_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du participant (recommandé: format carré, max 2MB)', null=True, upload_to='photos/participants/'),
        ),
    ]
